# Generated by Django 3.0.6 on 2020-07-17 13:58

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('taskid', models.UUIDField(default=uuid.uuid1, primary_key=True, serialize=False)),
                ('task_name', models.CharField(max_length=25)),
                ('task_progress', models.IntegerField(default=0)),
                ('task_time', models.DateTimeField(auto_now=True)),
                ('task_deadline_date', models.DateField(default=datetime.date(2020, 1, 1))),
                ('task_deadline_time', models.TimeField(default=datetime.time(11, 59, 59))),
                ('task_urgency', models.CharField(choices=[('low', 'low'), ('medium', 'medium'), ('high', 'high')], default='low', max_length=6)),
                ('task_status', models.BooleanField(default=False)),
                ('task_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtask_name', models.CharField(max_length=25)),
                ('subtask_time', models.DateTimeField(auto_now=True)),
                ('subtask_state', models.BooleanField(default=False)),
                ('task_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Card')),
            ],
        ),
    ]
