# Generated by Django 3.0.6 on 2020-07-27 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subcard',
            unique_together={('subtask_name', 'task_name')},
        ),
    ]
