# Generated by Django 3.0.6 on 2020-07-29 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200727_0454'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='task_deadline',
            field=models.DateTimeField(null=True),
        ),
    ]
